runtime: java11
env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
  GOOGLE_CLOUD_PROJECT: "prjtmngt-spring-boot"
handlers:
- url: /.*
  script: this field is required, but ignored
manual_scaling:
  instances: 1
