# This is a basic workflow to help you get started with Actions

name: Action Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-verions: 1.11
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify
        
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
          service_account: '{{ secrets.APPENGINE_DEPLOY_SA_EMAIL }}'
      
      - id: 'deploy'
        name: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: './target/ProjectManagement-0.0.1-SNAPSHOT.jar'
          project_id: '${{ secrets.GCP_PRORJECT }}'
      
      - name: 'show output'
        run: 'echo ${{ steps.deploy.outputs.url }}'
